/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalmorphing2;

import java.awt.Dimension;

/**
 *
 * @author Luca
 */
public class FinestraFinal extends javax.swing.JFrame 
{

    public FinestraFinal() 
    {
        initComponents();
        
    }

    public void setResultImage(Immagine a)
    {
        this.setSize(a.larghezza,a.altezza);
        displayFinal1.setImage(a);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayFinal1 = new finalmorphing2.DisplayFinal();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout displayFinal1Layout = new javax.swing.GroupLayout(displayFinal1);
        displayFinal1.setLayout(displayFinal1Layout);
        displayFinal1Layout.setHorizontalGroup(
            displayFinal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        displayFinal1Layout.setVerticalGroup(
            displayFinal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayFinal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(displayFinal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments

*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private finalmorphing2.DisplayFinal displayFinal1;
    // End of variables declaration//GEN-END:variables
}
